# Generated by Django 4.1.7 on 2023-03-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', help_text='Ce champ est obligatoire', upload_to='team/images')),
                ('fname', models.CharField(help_text='Ce champ est obligatoire', max_length=60)),
                ('lname', models.CharField(help_text='Ce champ est obligatoire', max_length=60)),
                ('description', models.TextField(help_text='Ce champ est obligatoire')),
                ('linkedin', models.CharField(help_text='Ce champ est obligatoire', max_length=250, null=True)),
                ('malt', models.CharField(help_text='Ce champ est obligatoire', max_length=250, null=True)),
                ('created_at', models.DateField(auto_now=True, verbose_name='Date de création')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Mise à jour')),
                ('job', models.ManyToManyField(help_text='Ce champ est obligatoire', related_name='jobs_team', to='jobs.job')),
                ('skills', models.ManyToManyField(help_text='Ce champ est obligatoire', related_name='skills_team', to='skills.skill')),
            ],
        ),
    ]
