# Generated by Django 4.1.7 on 2023-03-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ce champ est obligatoire', max_length=100)),
                ('description', models.TextField(help_text='Ce champ est obligatoire')),
                ('image', models.ImageField(default='', help_text='Ce champ est obligatoire', upload_to='services/images')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Date de création')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Mise à jour')),
            ],
        ),
    ]
