# Generated by Django 4.1.7 on 2023-03-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
