# Generated by Django 4.1.7 on 2023-03-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ce champ est obligatoire.', max_length=60)),
                ('image', models.ImageField(default='', help_text='Ce champ est obligatoire.', upload_to='technologies/images')),
                ('description', models.TextField(blank=True, help_text='La description de la technologie est optionelle.', null=True)),
                ('created_at', models.DateField(auto_now=True, verbose_name='Date de création')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Mise à jour')),
            ],
        ),
    ]
